global:
  scrape_interval: 15s
  evaluation_interval: 15s 

scrape_configs:
  # Configuração do back-end
  - job_name: "backend-monitoring"
    static_configs:
      - targets: ["${BACKEND_HOST}/metrics"]

  # Configuração do front-end
  - job_name: "frontend-monitoring"
    static_configs:
      - targets: ["${FRONTEND_HOST}/metrics"]

  # Configuração do banco de dados
  - job_name: "database-monitoring"
    static_configs:
      - targets: ["${DB_HOST}/metrics"]
