name: Go

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Start services with Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.0'

    - name: Run Generate Script
      run: go run scripts/generate/main.go

    - name: Run Migrate Script
      run: go run scripts/migrate/main.go

    - name: Run Seeds Script
      run: go run scripts/seeds/main.go

    - name: Build
      run: go run main.go

    - name: Test
      run: |
        echo "Running all *_test.go files:"
        find . -name '*_test.go'  # Lista todos os arquivos de teste
        go test -v ./...
