name: Unit tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: ci_env
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go Environment
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.0'

    - name: Generate Required Files
      run: go run scripts/generate/main.go

    - name: Run Unit Tests
      run: make test
